EHRI/ehri-rest

assembly/pom.xml, ehri-cmdline/pom.xml, ehri-definitions/pom.xml, ehri-extension-sparql/pom.xml, ehri-extension/pom.xml, ehri-frames/pom.xml, ehri-importers/pom.xml, pom.xml
- Make all module versions consistent at 0.9-SNAPSHOT
- Set up deployment to an EHRI artifactory instance
The following Stackoverflow answer was useful:
https://stackoverflow.com/questions/5726291/updating-version-numbers-of-modules-in-a-multi-module-maven-project
=> Step one in improving deployment and versioning.

ehri-importers/src/main/java/eu/ehri/project/importers/CsvAuthoritativeItemImporter.java, ehri-importers/src/main/java/eu/ehri/project/importers/EadImporter.java, ehri-importers/src/main/resources/bundesarchive.properties, ehri-importers/src/main/resources/its-provenance.properties, ehri-importers/src/main/resources/jmp.properties, ehri-importers/src/main/resources/vc_ara.properties, ehri-importers/src/test/java/eu/ehri/project/importers/CsvAuthItemImporterTest.java, ehri-importers/src/test/java/eu/ehri/project/importers/IfzTest.java, ehri-importers/src/test/java/eu/ehri/project/importers/Jmp130Test.java, ehri-importers/src/test/java/eu/ehri/project/importers/VC_ARAImporterTest.java, ehri-importers/src/test/resources/BA_split.xml, ehri-importers/src/test/resources/JMP-130.xml, ehri-importers/src/test/resources/araEad.xml, ehri-importers/src/test/resources/araVcEad.xml, ehri-importers/src/test/resources/ifz_ED.xml, ehri-importers/src/test/resources/logback-test.xml, ehri-importers/src/test/resources/wien_victims.csv
plus: CsvAuthoritativeItemImporter will actually create AuthoritativeItem, instead of Concept
=> Debug statements not printed during test, in logback-test.xml

LICENSE, checkstyle.xml, java.header, pom.xml
This is the easy step in #103 , the "hard" step is adding the preamble to all code files.
=> Change LICENSE to EUPL v1.1, add license to pom

ehri-extension/src/main/java/eu/ehri/extension/AdminResource.java, fabfile.py
- allow updating internal lucene index from web service
- tar online backups by default
=> Grab bag of minor tweaks

ehri-definitions/src/main/java/eu/ehri/project/definitions/Ontology.java, ehri-frames/src/main/java/eu/ehri/project/models/base/Actioner.java, ehri-frames/src/main/java/eu/ehri/project/models/events/SystemEvent.java, ehri-frames/src/main/java/eu/ehri/project/persistence/ActionManager.java, ehri-frames/src/test/java/eu/ehri/project/persistence/ActionManagerTest.java
This fixes #132, but should not be released till all the ingests and
updating has stabilised.
=> Change label of action-link->event relationship and simplify event->subject count.

ehri-extension/src/test/java/eu/ehri/extension/test/UserProfileRestClientTest.java, ehri-frames/src/main/java/eu/ehri/project/models/UserProfile.java
Due to badly-named functions these relationships singular, rather than unique between source and destination.
Fixes #135.
=> Fix stupid bug breaking watching/following

src/site/markdown/identifiers.md, src/site/markdown/permissions.md
This replaces a few "TODO"s with actual information.
=> Finish documentation on permissions and identifiers

ehri-cmdline/src/main/java/eu/ehri/project/commands/DeleteEntities.java, ehri-extension/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-frames/src/main/java/eu/ehri/project/acl/AclManager.java
There are still some instances in the tests but I'm not so worried about them.
=> Fix a couple of instances in production code where closeable iterables weren't closed

assembly/pom.xml, ehri-cmdline/pom.xml, ehri-definitions/pom.xml, ehri-definitions/src/main/java/eu/ehri/project/definitions/EventTypes.java, ehri-extension-sparql/pom.xml, ehri-extension/pom.xml, ehri-extension/src/main/java/eu/ehri/extension/AbstractRestResource.java, ehri-extension/src/main/java/eu/ehri/extension/SystemEventResource.java, ehri-extension/src/main/java/eu/ehri/extension/UserProfileResource.java, ehri-extension/src/main/java/eu/ehri/extension/VersionResource.java, ehri-extension/src/test/java/eu/ehri/extension/test/BaseRestClientTest.java, ehri-extension/src/test/java/eu/ehri/extension/test/SystemEventRestClientTest.java, ehri-extension/src/test/java/eu/ehri/extension/test/VersionRestClientTest.java, ehri-frames/pom.xml, ehri-frames/src/main/java/eu/ehri/project/persistence/ActionManager.java, ehri-frames/src/main/java/eu/ehri/project/utils/pipes/AggregatorPipe.java, ehri-frames/src/main/java/eu/ehri/project/views/EventViews.java, ehri-frames/src/main/java/eu/ehri/project/views/Query.java, ehri-frames/src/main/java/eu/ehri/project/views/UserProfileViews.java, ehri-frames/src/test/java/eu/ehri/project/models/events/SystemEventTest.java, ehri-frames/src/test/java/eu/ehri/project/utils/pipes/AggregatorPipeTest.java, ehri-frames/src/test/java/eu/ehri/project/views/EventViewsTest.java, ehri-frames/src/test/java/eu/ehri/project/views/UserProfileViewsTest.java, ehri-importers/pom.xml, pom.xml
- Add a general purpose, generic aggregation pipe class
- Add a view class for user interaction events. Since we can't
currently distinguish between interactions and events and
lifecycle events, watching, following, and blocking do not currently
log.
- Move various web service method docs to the resource javadoc
- Refactor event resource to handle common parameters
- Move version access to its own resource class
- Remove reliance on Query object in event streams
- Update version number to 0.10.1
=> Implement event aggregation:

scripts/publish_docs.sh
This requires the [docs repository](https://github/EHRI/EHRI.github.io) as an argument.
=> Add a script for publishing the API docs

assembly/pom.xml, ehri-cmdline/pom.xml, ehri-definitions/pom.xml, ehri-extension-sparql/pom.xml, ehri-extension/pom.xml, ehri-extension/src/main/java/eu/ehri/extension/AbstractRestResource.java, ehri-frames/pom.xml, ehri-importers/pom.xml, pom.xml
=> URLdecode log message headers.

ehri-cmdline/src/main/java/eu/ehri/project/commands/Check.java, ehri-cmdline/src/main/java/eu/ehri/project/commands/DeleteEntities.java, ehri-cmdline/src/main/java/eu/ehri/project/commands/EntityAdd.java, ehri-cmdline/src/main/java/eu/ehri/project/commands/GetEntity.java, ehri-cmdline/src/main/java/eu/ehri/project/commands/ListEntities.java, ehri-cmdline/src/main/java/eu/ehri/project/commands/UserListEntities.java, ehri-extension/src/main/java/eu/ehri/extension/AbstractAccessibleEntityResource.java, ehri-extension/src/main/java/eu/ehri/extension/AbstractRestResource.java, ehri-frames/src/main/java/eu/ehri/project/core/impl/BlueprintsGraphManager.java, ehri-frames/src/main/java/eu/ehri/project/models/EntityClass.java, ehri-frames/src/main/java/eu/ehri/project/persistence/Bundle.java, ehri-frames/src/main/java/eu/ehri/project/persistence/BundleDAO.java, ehri-frames/src/main/java/eu/ehri/project/persistence/BundleValidator.java, ehri-frames/src/main/java/eu/ehri/project/persistence/Serializer.java, src/site/markdown/gotchas.md, src/site/markdown/install.md
- rename method to get Java class from entity type
- fix some Javadoc issues with JDK 8
- small documentation fixes
=> Cleanups and doc fixes

ehri-extension/src/main/java/eu/ehri/extension/ImportResource.java, ehri-extension/src/test/java/eu/ehri/extension/test/ImportResourceRestClientTest.java, ehri-extension/src/test/resources/abwehr.xml, ehri-extension/src/test/resources/eag-2896.xml, ehri-importers/src/test/java/eu/ehri/project/importers/CsvAuthItemImporterTest.java
The EAD endpoint actually does both of these with the appropriate handler/importer class, despite its name.
Also generalised path list / archive / single file stream handling and applied it to the CSV importer.
=> Refactor import handlers, adding endpoints for EAC and EAG types.

ehri-extension/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-frames/src/main/java/eu/ehri/project/core/impl/Neo4jGraphManager.java, ehri-frames/src/test/java/eu/ehri/project/core/impl/Neo4jGraphManagerTest.java
Also add a tools function to set labels for existing vertices.
This functionality will mainly be used for analytics via Cypher.
=> Make the Neo4j2 graph manager set labels in accordance with the type.

ehri-extension/src/main/java/eu/ehri/extension/VocabularyResource.java, ehri-extension/src/test/java/eu/ehri/extension/test/BaseRestClientTest.java, ehri-extension/src/test/java/eu/ehri/extension/test/CvocVocabularyClientTest.java, ehri-extension/src/test/java/eu/ehri/extension/test/ToolsRestClientTest.java, ehri-frames/src/main/java/eu/ehri/project/persistence/BundleDAO.java, ehri-frames/src/test/resources/fixtures/testdata.yaml, ehri-importers/pom.xml, ehri-importers/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java, ehri-importers/src/main/java/eu/ehri/project/exporters/cvoc/SkosExporter.java, ehri-importers/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-importers/src/main/java/eu/ehri/project/importers/cvoc/SkosRDFVocabulary.java, ehri-importers/src/main/java/eu/ehri/project/importers/util/Helpers.java, ehri-importers/src/test/java/eu/ehri/project/exporters/cvoc/JenaSkosExporterTest.java, ehri-importers/src/test/java/eu/ehri/project/importers/cvoc/AbstractSkosTest.java, ehri-importers/src/test/java/eu/ehri/project/importers/cvoc/JenaSkosImporterTest.java, ehri-importers/src/test/java/eu/ehri/project/importers/cvoc/OwlApiSkosImporterTest.java, ehri-importers/src/test/java/eu/ehri/project/importers/cvoc/XmlSkosImporterTest.java, ehri-importers/src/test/java/eu/ehri/project/importers/util/HelpersTest.java, ehri-importers/src/test/resources/logback-test.xml
This currently resides in the importers module, need to rename that 'io'.
- Moved common SKOS mappings to the vocabulary class.
- added endpoint to export vocabularies to the Vocabulary resource
=> Added a SKOS exporter class.

ehri-io/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java, ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
File under: things that break with streaming responses. :|
=> Fix a critical bug where the SKOS exporter didn't close its TX.

ehri-core/src/main/java/eu/ehri/project/views/EventViews.java, ehri-core/src/test/java/eu/ehri/project/views/EventViewsTest.java
This is done by aggregating those user's action streams directly.
=> Work around slow scanning of the event stream for individual users.

ehri-core/src/main/java/eu/ehri/project/views/EventViews.java
Item and user event streams serve as an index in this case, though when filtering for more than one of each we have to sort the events by timestamp, which is less efficient.
Fixes #60.
=> User action/history streams directly when filtering events for users/items.

Dockerfile, ehri-cli/pom.xml, ehri-core/pom.xml, ehri-io/pom.xml, ehri-ws-sparql/pom.xml, ehri-ws/pom.xml, scripts/builddb, src/site/markdown/install.md
Additional minor fix to legacy script.
=> Update Neo4j to 2.3.2

ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/AbstractSkosTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/JenaSkosImporterTest.java, ehri-io/src/test/resources/cvoc/scriptcode.n3
=> Handle a script code in SKOS RDF literal language tags.

ehri-ws/src/main/java/eu/ehri/extension/AnnotationResource.java, ehri-ws/src/main/java/eu/ehri/extension/LinkResource.java
Also apply some consistency improvements elsewhere.
=> Fix erroneous limit applied when fetching an item's links.

ehri-io/src/main/java/eu/ehri/project/importers/base/MapImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/SkosImporter.java, ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
Additional small date parsing tweaks.
=> Add skos import base URI

ehri-ws/src/main/java/eu/ehri/extension/RepositoryResource.java, ehri-ws/src/test/java/eu/ehri/extension/test/RepositoryRestClientTest.java
This is quite nice and efficient compared to other methods.
=> Add code to export all repository fonds as EAD in one zip file.

ehri-cli/pom.xml, ehri-core/pom.xml, ehri-io/pom.xml, ehri-ws-sparql/pom.xml, ehri-ws/pom.xml
This has a fix for quite a major deficiency in 2.3.3, COLLECT(DISTINCT) with null elements throwing an error.
=> Update Neo4j to 2.3.4

fabfile.py
Mainly concerning Solr 6, which is now running on Jetty and not Tomcat.
=> Update the fabfile for various deployment-related changes.

Dockerfile, build/pom.xml, ehri-cli/pom.xml, ehri-cli/src/main/java/eu/ehri/project/commands/GraphViz.java, ehri-core/pom.xml, ehri-core/src/main/java/eu/ehri/project/core/impl/Neo4jGraphManager.java, ehri-core/src/main/java/eu/ehri/project/core/impl/neo4j/Neo4j2Graph.java, ehri-core/src/main/java/eu/ehri/project/core/impl/neo4j/Neo4j2Vertex.java, ehri-io/pom.xml, ehri-ws-sparql/pom.xml, ehri-ws/pom.xml, fabfile.py
- update fabfile
- fix logging config for command-line use
- update the Dockerfile
=> Grab-bag of fixes

build/pom.xml, ehri-cli/pom.xml, ehri-cli/src/main/java/eu/ehri/project/commands/GraphViz.java, ehri-core/pom.xml, ehri-core/src/main/java/eu/ehri/project/core/impl/neo4j/Neo4j2Graph.java, ehri-core/src/main/java/eu/ehri/project/persistence/DataConverter.java, ehri-core/src/test/java/eu/ehri/project/api/ApiCrudTest.java, ehri-core/src/test/java/eu/ehri/project/core/GraphManagerTest.java, ehri-cypher/pom.xml, ehri-io/pom.xml, ehri-ws-sparql/pom.xml, ehri-ws/pom.xml, pom.xml
Since Ivy/SBT now handles Maven vars it should hopefully be safe to do this.
=> Minor fixes: build issues, POM redundency, Javadocs, deprecation.

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java, ehri-ws-graphql/src/test/java/eu/ehri/extension/test/GraphQLResourceClientTest.java, ehri-ws-graphql/src/test/resources/testquery.graphql
Also, make concept related items a list rather than a connection.
=> Add a field for fetching ancestors of a documentary unit.

ehri-ws-graphql/src/main/java/eu/ehri/extension/GraphQLResource.java, ehri-ws-graphql/src/main/java/eu/ehri/extension/errors/ExecutionError.java, ehri-ws-graphql/src/main/java/eu/ehri/extension/errors/ExecutionException.java, ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java, ehri-ws-graphql/src/test/resources/testquery.graphql
Also prevent NPE when no location is given in an error.
=> Fix a class cast error fetching descriptions when the fetcher returns entities

ehri-cypher/src/test/java/eu/ehri/project/cypher/ProceduresTest.java
Hopefully this prevents the sporadic AsyncronousBufferClose exception we sometimes see.
=> Test fix: ensure session is auto-closed.

ehri-core/src/main/java/eu/ehri/project/tools/IdRegenerator.java, ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-ws/src/test/java/eu/ehri/extension/test/ToolsResourceClientTest.java, pom.xml
This is more flexible.
Additionally, bump Neo4j to latest maintenance release.
=> Change ID regeneration helper to accept a list of current IDs.

ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
The input is a mapping of current global ID to new local identifier, from which a new global ID will be automatically derived.
=> Add a tool endpoint to rename items (local ID) in bulk via a CSV.

build/pom.xml, ehri-cli/pom.xml, ehri-core/pom.xml, ehri-cypher/pom.xml, ehri-definitions/pom.xml, ehri-io/pom.xml, ehri-io/src/main/java/eu/ehri/project/importers/ImportLog.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/json/BatchOperations.java, ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java, ehri-io/src/test/java/eu/ehri/project/importers/base/MapImporterTest.java, ehri-ws-graphql/pom.xml, ehri-ws-oaipmh/pom.xml, ehri-ws/pom.xml, ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java, ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-ws/src/main/java/eu/ehri/extension/providers/ImportLogProvider.java, ehri-ws/src/main/java/eu/ehri/extension/providers/TableProvider.java, ehri-ws/src/main/java/eu/ehri/extension/utils/Table.java, ehri-ws/src/test/java/eu/ehri/extension/test/AbstractResourceClientTest.java, ehri-ws/src/test/java/eu/ehri/extension/test/ToolsResourceClientTest.java, pom.xml
Refactor various WS-related components.
Bump versions, since this is a significant API change.
=> Add a table data type with a provider for CSV-shaped data.

build/pom.xml, ehri-cli/pom.xml, ehri-core/pom.xml, ehri-cypher/pom.xml, ehri-definitions/pom.xml, ehri-io/pom.xml, ehri-ws-graphql/pom.xml, ehri-ws-oaipmh/pom.xml, ehri-ws/pom.xml, ehri-ws/src/main/java/eu/ehri/extension/errors/MissingOrInvalidUser.java, ehri-ws/src/main/java/eu/ehri/extension/errors/WebDeserializationError.java, ehri-ws/src/main/java/eu/ehri/extension/errors/mappers/AccessDeniedMapper.java, ehri-ws/src/main/java/eu/ehri/extension/errors/mappers/DeserializationErrorMapper.java, ehri-ws/src/main/java/eu/ehri/extension/errors/mappers/ItemNotFoundMapper.java, ehri-ws/src/main/java/eu/ehri/extension/errors/mappers/MissingOrInvalidUserErrorMapper.java, ehri-ws/src/main/java/eu/ehri/extension/errors/mappers/ModeViolationMapper.java, ehri-ws/src/main/java/eu/ehri/extension/errors/mappers/PermissionDeniedMapper.java, ehri-ws/src/main/java/eu/ehri/extension/errors/mappers/ValidationErrorMapper.java, ehri-ws/src/main/java/eu/ehri/extension/providers/JsonMessageBodyHandler.java, ehri-ws/src/test/java/eu/ehri/extension/test/DocumentaryUnitResourceClientTest.java, ehri-ws/src/test/java/eu/ehri/extension/test/PermissionResourceClientTest.java, ehri-ws/src/test/java/eu/ehri/extension/test/RepositoryResourceClientTest.java, ehri-ws/src/test/java/eu/ehri/extension/test/VirtualUnitResourceClientTest.java, pom.xml
- Always return JSON
- Make permission errors return 403 (forbidden) instead of 401
- Clean up serialization code
=> Attempt to make various HTTP error responses more consistent.

ehri-core/src/main/java/eu/ehri/project/tools/Linker.java, ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java, ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java, ehri-ws/src/main/java/eu/ehri/extension/base/AbstractResource.java
This allows groups to perform certain actions, e.g. automated ones.
=> Allow an Actioner instead of just a UserProfile in certain places.

ehri-cli/src/main/java/eu/ehri/project/commands/Check.java
This can be run from the command line to, say, validate a backup in a basic manner.
=> Add a set of basic validations to the check cmd.

ehri-io/src/main/java/eu/ehri/project/exporters/ead/Ead2002Exporter.java, ehri-io/src/main/resources/ead2002.properties
Add <odd> as a notes field and remove superfluous rendering of
datesOfDescriptions.
=> More EAD I/O fixes.

README.md, ehri-cli/src/main/java/eu/ehri/project/commands/UserAdd.java, ehri-cli/src/test/java/eu/ehri/project/commands/UserAddTest.java, scripts/initdb.sh
Also add note to the README and fix the command line usage of the tool that did this...
=> Add Docker option to create admin user at initialization time.

scripts/initdb.sh
=> Fix unset variable when no user given.

ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java, ehri-definitions/src/main/java/eu/ehri/project/definitions/Ontology.java, ehri-io/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/SkosImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/SkosRDFVocabulary.java, ehri-io/src/test/java/eu/ehri/project/exporters/cvoc/JenaSkosExporterTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/AbstractSkosTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/EventsSkosImporterTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/JenaSkosImporterTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/JoodsRaadTest.java, ehri-io/src/test/resources/cvoc/geonames.ttl, ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
Involves some hacks for assumptions that don't quite translate between the multi-description and multilingual properties...
=> Changes to SKOS importer to facilitate geonames ingest.

ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java, ehri-ws/src/test/java/eu/ehri/extension/test/ImportResourceResourceClientTest.java
=> Refactor exception handling in import resource.

Dockerfile, ehri-cli/pom.xml, ehri-core/pom.xml, ehri-io/pom.xml, ehri-ws-graphql/pom.xml, ehri-ws-oaipmh/pom.xml, ehri-ws/pom.xml
This is a bit dubious, since the impl will clash with others e.g. Neo4j might include in the future, but it's easier than handling it manually.
=> Another fix to logging: re-include logback in package.

ehri-core/src/main/java/eu/ehri/project/models/cvoc/Concept.java
Fixes child count being out-of-date on frontend.
=> Use dynamic child count property on Concept model

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java, ehri-ws-graphql/src/test/java/eu/ehri/extension/test/GraphQLResourceClientTest.java, ehri-ws-graphql/src/test/resources/testquery.graphql
=> Consider item type when doing id lookups.

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java, ehri-ws-graphql/src/test/resources/testquery.graphql
Also use a fragment in tests for fetching the name variable fordescribed items.
=> Add a `Described` interface for described items.

ehri-core/src/main/java/eu/ehri/project/core/impl/Neo4jGraphManager.java, ehri-core/src/main/java/eu/ehri/project/models/DatePeriod.java, ehri-core/src/main/java/eu/ehri/project/models/Link.java, ehri-core/src/main/java/eu/ehri/project/models/annotations/Indexed.java, ehri-core/src/main/java/eu/ehri/project/models/base/Description.java, ehri-core/src/main/java/eu/ehri/project/models/utils/ClassUtils.java, ehri-core/src/test/java/eu/ehri/project/models/utils/ClassUtilsTest.java
Some properties are too large to reasonably index and liable to cause problems if we do.
=> Instead of indexing all properties, add an indexed flag to specific ones

ehri-ws-graphql/src/main/java/eu/ehri/extension/GraphQLResource.java, ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLQuery.java, ehri-ws-graphql/src/test/java/eu/ehri/extension/test/GraphQLResourceClientTest.java
No longer stringified, which simplifies things a bit.
=> Change the way variables are handled for GraphiQL 0.8+ compat.

build/pom.xml, ehri-core/pom.xml, ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java, ehri-core/src/main/java/eu/ehri/project/persistence/BundleManager.java, ehri-core/src/main/java/eu/ehri/project/persistence/DataConverter.java, ehri-core/src/test/java/eu/ehri/project/persistence/BundleTest.java
Note: should try out https://github.com/flipkart-incubator/zjsonpatch instead since it seems to be more actively maintained.
=> Add a method to debug changes using JSON-Patch

ehri-io/src/main/java/eu/ehri/project/importers/json/BatchOperations.java, ehri-io/src/main/java/eu/ehri/project/utils/Table.java, ehri-ws/src/main/java/eu/ehri/extension/BatchResource.java, ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java, ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-ws/src/main/java/eu/ehri/extension/base/AbstractResource.java, ehri-ws/src/main/java/eu/ehri/extension/providers/TableProvider.java, ehri-ws/src/test/java/eu/ehri/extension/test/BatchResourceClientTest.java, ehri-ws/src/test/java/eu/ehri/extension/test/ImportResourceClientTest.java
Also change the way delete works to take a table as input.
=> Move batch update/delete to their own WS namespace/resource.

ehri-core/src/main/java/eu/ehri/project/models/utils/JavaHandlerUtils.java, ehri-io/src/main/java/eu/ehri/project/importers/base/SaxXmlHandler.java, ehri-io/src/main/java/eu/ehri/project/importers/csv/UkrainianUnitImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/eac/EacHandler.java, ehri-io/src/main/java/eu/ehri/project/importers/eac/EacImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/ead/EadHandler.java, ehri-io/src/main/java/eu/ehri/project/importers/ead/EadImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/ead/UshmmHandler.java, ehri-io/src/main/java/eu/ehri/project/importers/ead/VirtualEadHandler.java, ehri-io/src/main/java/eu/ehri/project/importers/ead/VirtualEadImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/managers/CsvImportManager.java, ehri-io/src/main/java/eu/ehri/project/importers/managers/SaxImportManager.java, ehri-io/src/main/java/eu/ehri/project/importers/properties/XmlImportProperties.java, ehri-io/src/main/java/eu/ehri/project/importers/util/ImportHelpers.java, ehri-ws/src/main/java/eu/ehri/extension/base/AbstractAccessibleResource.java
Turn log level up to TRACE to see all the gory details...
Fixes #335
=> Change log levels for various ingest-related guff.

ehri-io/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/SkosRDFVocabulary.java, ehri-io/src/test/java/eu/ehri/project/exporters/cvoc/JenaSkosExporterTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/GhettosImporterTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/GhettosImporterV20140831Test.java, ehri-io/src/test/resources/cvoc/ghettos.rdf, ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
- Disable relative URIs
- Use description identifier for script code
Fixes #407
=> RDF export fixes

ehri-cypher/src/main/java/eu/ehri/project/cypher/Functions.java, ehri-cypher/src/main/java/eu/ehri/project/cypher/Procedures.java, ehri-cypher/src/test/java/eu/ehri/project/cypher/FunctionsTest.java
=> Add functions for EHRI utilities and deprecate the procedures.

ehri-ws/src/test/java/eu/ehri/extension/test/helpers/ServerRunner.java, ehri-ws/src/test/resources/jetty-logging.properties
This works better w/ Neo4j 3.4
=> Configure Jetty's log using a property file

ehri-ws-oaipmh/src/main/java/eu/ehri/project/oaipmh/OaiPmhData.java, ehri-ws-oaipmh/src/test/java/eu/ehri/project/oaipmh/OaiPmhExporterTest.java
This allows deterministic ordering for tests
=> Provide a non-default sort option on OAI-PMH data service

ehri-io/src/main/java/eu/ehri/project/importers/json/BatchOperations.java
This allows items which are not found to be ignored.
=> Better tolerant behaviour on batch updates

ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/SkosImporter.java, ehri-io/src/test/java/eu/ehri/project/exporters/cvoc/JenaSkosExporterTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/CampsImporterTest.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/CampsV2_1Test.java, ehri-io/src/test/java/eu/ehri/project/importers/cvoc/GhettosImporterV20140831Test.java, ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
This is in line with other importers.
=> Default SKOS importer to not update items unless told to explicitly.

ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
This is in line with other tool endpoints.
=> Add a commit parameter to the rename endpoint.

ehri-cypher/src/main/java/eu/ehri/project/cypher/Functions.java, ehri-cypher/src/test/java/eu/ehri/project/cypher/FunctionsTest.java, ehri-io/src/main/resources/allowedNodeProperties.csv, ehri-io/src/test/java/eu/ehri/project/exporters/ead/Ead2002ExporterTest.java
Also make archivists note single valued.
=> Add a Cypher function for joining arrays.

ehri-core/src/main/java/eu/ehri/project/models/cvoc/Vocabulary.java, ehri-core/src/test/java/eu/ehri/project/models/cvoc/VocabularyTest.java, ehri-ws/src/main/java/eu/ehri/extension/CvocConceptResource.java, ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
This behaviour is more in line with other hierarchical types
=> Make vocab resource list only top concepts by default.

ehri-core/src/main/java/eu/ehri/project/api/impl/ApiImpl.java, ehri-core/src/test/java/eu/ehri/project/api/ApiCrudTest.java
This prevents dependent items which have meaningful IDs (such as descriptions) generating truncated IDs due to the lack of the full scope path.
=> Set the scope of update actions properly.

ehri-core/src/main/java/eu/ehri/project/api/ConceptsApi.java, ehri-core/src/main/java/eu/ehri/project/api/impl/ConceptsApiImpl.java, ehri-ws/src/main/java/eu/ehri/extension/CvocConceptResource.java, ehri-ws/src/main/java/eu/ehri/extension/base/ChildResource.java
Currently only implemented for concepts, where the parents are the
broader terms.
=> Add another WS interface for setting parent(s) of a given item.

ehri-ws/src/main/java/eu/ehri/extension/AuthoritativeSetResource.java, ehri-ws/src/main/java/eu/ehri/extension/RepositoryResource.java
Also add more params to existing repository endpoint.
=> Add a batch import endpoint to auth set resource.

ehri-core/src/main/java/eu/ehri/project/persistence/BundleValidator.java, ehri-core/src/test/java/eu/ehri/project/persistence/BundleValidatorTest.java
This means we can report better contextual ID generation errors, whilst still ensuring the whole bundle is valid.
=> Check duplicate IDs in bundle twice, once among rels and once globally

ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
=> Add a per-item description ID regenerator

build/pom.xml, ehri-cli/pom.xml, ehri-core/pom.xml, ehri-core/src/main/java/eu/ehri/project/api/Api.java, ehri-core/src/main/java/eu/ehri/project/api/impl/ApiImpl.java, ehri-core/src/test/java/eu/ehri/project/api/ApiDescriptionsTest.java, ehri-cypher/pom.xml, ehri-definitions/pom.xml, ehri-io/pom.xml, ehri-ws-graphql/pom.xml, ehri-ws-oaipmh/pom.xml, ehri-ws/pom.xml, ehri-ws/src/main/java/eu/ehri/extension/GenericResource.java, ehri-ws/src/test/java/eu/ehri/extension/test/DescriptionResourceClientTest.java, pom.xml
Descriptions are now managed via the full bundle. TODO: come up w/ a better transactional way to manage access points.
Also bump version to 0.13.11.
=> Cleanup API, removing CRUD for descriptions.

ehri-core/src/main/java/eu/ehri/project/models/DocumentaryUnit.java, ehri-io/src/main/java/eu/ehri/project/importers/ead/EadSync.java, ehri-io/src/test/java/eu/ehri/project/importers/ead/EadSyncTest.java
=> Preserve membership of virtual collections when syncing EAD

ehri-core/src/test/resources/fixtures/testdata.yaml, ehri-io/src/main/java/eu/ehri/project/exporters/ead/Ead2002Exporter.java, ehri-io/src/test/java/eu/ehri/project/exporters/ead/Ead2002ExporterTest.java, ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java
Also add related items to the GraphQL data schema for repositories.
This amount of copy links is rather unsatisfactory but shall be improved later.
=> Add copy links w/ descriptions to EAD export originalsloc section.

ehri-io/src/main/java/eu/ehri/project/importers/properties/XmlImportProperties.java, ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
This should be better than a local file if the properties are stored on the Cloud.
=> Allow loading ingest properties files via an URL

ehri-cli/pom.xml, ehri-core/pom.xml, ehri-cypher/pom.xml, ehri-io/pom.xml, ehri-ws-graphql/pom.xml, ehri-ws-oaipmh/pom.xml, ehri-ws/pom.xml, pom.xml
=> Update some dependencies

ehri-core/src/main/java/eu/ehri/project/persistence/DataConverter.java, ehri-io/src/main/java/eu/ehri/project/importers/ImportLog.java, ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/json/BatchOperations.java, ehri-io/src/main/java/eu/ehri/project/importers/links/LinkImporter.java, ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java, ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java, ehri-ws/src/main/java/eu/ehri/extension/base/AbstractAccessibleResource.java, ehri-ws/src/main/java/eu/ehri/extension/base/AbstractResource.java, ehri-ws/src/test/java/eu/ehri/extension/test/ImportResourceClientTest.java
This should make it easier to associate a given import task with its items from the frontend.
Various other cleanups
=> Add the event ID to the import log

ehri-core/src/main/java/eu/ehri/project/acl/AclManager.java, ehri-core/src/main/java/eu/ehri/project/persistence/BundleManager.java, ehri-io/src/main/java/eu/ehri/project/utils/Table.java, ehri-ws/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java, ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java, ehri-ws/src/test/java/eu/ehri/extension/test/DocumentaryUnitResourceClientTest.java
=> Add new WS methods for renaming and deleting full collections

ehri-ws/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java, ehri-ws/src/test/java/eu/ehri/extension/test/DocumentaryUnitResourceClientTest.java
Now send in POST body. My brain has obviously checked out for the year.
=> Fix (obvious!?) encoding bug sending local identifier in method path

build/pom.xml
=> Add missing dependency for commons-collection4 in package

build/pom.xml, ehri-cli/pom.xml, ehri-cli/src/main/java/eu/ehri/project/commands/BaseCommand.java, ehri-cli/src/main/java/eu/ehri/project/commands/GenSchema.java, ehri-core/pom.xml, ehri-io/pom.xml, ehri-ws-graphql/pom.xml, ehri-ws-oaipmh/pom.xml, ehri-ws/pom.xml
This should avoid a collision w/ Neo4j packaged log dep
=> Remove logging dep from CLI module and make it a test dep for others

ehri-core/src/main/java/eu/ehri/project/models/base/Addressable.java, ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java, ehri-ws-graphql/src/test/java/eu/ehri/project/graphql/GraphQLImplTest.java, ehri-ws-graphql/src/test/java/eu/ehri/project/ws/test/GraphQLResourceClientTest.java, ehri-ws-graphql/src/test/resources/testquery.graphql
Although this is pretty sketchy, the old deprecated way had some pretty bad edge-case bugs.
=> Replace field-based data fetchers with new coordinate-based wiring

ehri-core/src/test/resources/fixtures/testdata.yaml, ehri-cypher/src/main/java/eu/ehri/project/cypher/Functions.java, ehri-cypher/src/main/java/eu/ehri/project/cypher/Procedures.java, ehri-io/src/main/java/eu/ehri/project/definitions/messages.properties, ehri-io/src/main/java/eu/ehri/project/utils/LanguageHelpers.java, ehri-io/src/test/java/eu/ehri/project/utils/LanguageHelpersTest.java, ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java, ehri-ws-graphql/src/test/java/eu/ehri/project/ws/test/GraphQLResourceClientTest.java, ehri-ws-graphql/src/test/resources/testquery.graphql
- fix missing fields on Country model
- add hack for missing country codes (XK, MK)
=> GraphQL fixes

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java, ehri-ws-graphql/src/test/java/eu/ehri/project/ws/test/GraphQLResourceClientTest.java, ehri-ws-graphql/src/test/resources/testquery.graphql
Also add a fetcher for access point IDs
=> Add missing data fetcher for GraphQL context.body field
