EHRI/ehri-rest

ehri-importers/src/main/java/eu/ehri/project/importers/AbstractImportManager.java
ehri-importers/src/main/java/eu/ehri/project/importers/AbstractImporter.java
ehri-importers/src/main/java/eu/ehri/project/importers/CsvImportManager.java
ehri-importers/src/main/java/eu/ehri/project/importers/MapImporter.java
ehri-importers/src/main/java/eu/ehri/project/importers/SaxImportManager.java
ehri-importers/src/test/java/eu/ehri/project/importers/AbstractImporterTest.java
ehri-importers/src/test/java/eu/ehri/project/importers/DansEadImporterTest.java
ehri-importers/src/test/java/eu/ehri/project/importers/FinlandXmlImporterTest.java
ehri-importers/src/test/java/eu/ehri/project/importers/IcaAtomEadImporterTest.java
ehri-importers/src/test/java/eu/ehri/project/importers/ItsTest.java
ehri-importers/src/test/java/eu/ehri/project/importers/WienerLibraryTest.java
ehri-importers/src/test/java/eu/ehri/project/importers/YadVashemTest.java

XmlImportManager -> AbstractImportManager
In #14 the hierarchy of `Importer`s and `ImportManager`s is discussed and deemed strange.
For example, the `CsvImportManager` is a subclass of `XmlImportManager`. This has been
changed by renaming the `XmlImportManager` to `AbstractImportManager` - it had not much to
do with XML anyway, so this makes sense.
Some tests that referenced the `AbstractImportManager` have been refactored to use the
instance in the `AbstractImporterTest`, which now also has
```
protected Repository repository;
// Depends on fixtures
protected final String TEST_REPO = "r1";
```
and `setUp()` and `tearDown()` methods to support test setup (`@Before`) and tearing down
(`@After`).
Added or updated javadoc comments in several locations.
Remove old javadoc param, add more …

Refactor ImporterManagers + tests (fixes #14)

---

ehri-frames/src/main/java/eu/ehri/project/utils/TxCheckedNeo4jGraph.java

Because we have a single, serialized audit event log in the graph, this
somewhat limits the extent to which concurrent graph modifications can
take place. Certain actions, such as watching items or following
users can happily work concurrently because they do not modify the event
log, but adding, modifying, or deleting data actions effectively need to hold a
lock on the event chain.
Unfortunately, Neo4j does not know that most transactions modify the
global event root, so it doesn't lock this node. This means that logged
concurrent transactions sometimes fail because they try to modify the
event root's head relationship and then discover it's already been changed
by another thread. This doesn't lead to any data corruption since the
transaction is just rolled back, but it does …

Prevent occasional transaction failures by locking the event chain root at TX start.

---

ehri-extension/src/main/java/eu/ehri/extension/ToolsResource.java
ehri-extension/src/test/java/eu/ehri/extension/test/ToolsRestClientTest.java
ehri-frames/src/main/java/eu/ehri/project/core/GraphManager.java
ehri-frames/src/main/java/eu/ehri/project/core/impl/BlueprintsGraphManager.java
ehri-frames/src/main/java/eu/ehri/project/models/idgen/IdGenerator.java
ehri-frames/src/main/java/eu/ehri/project/tools/IdRegenerator.java
ehri-frames/src/main/java/eu/ehri/project/utils/Slugify.java
ehri-frames/src/test/java/eu/ehri/project/models/utils/ClassUtilsTest.java
ehri-frames/src/test/java/eu/ehri/project/tools/IdRegeneratorTest.java
ehri-frames/src/test/java/eu/ehri/project/utils/SlugifyTest.java
ehri-importers/src/test/java/eu/ehri/project/importers/ItsTest.java

- slugify no longer allows leading or trailing non-alphanumeric chars
- add an IdRegenerator helper class
- add a couple of ways to call it from the web service
- re-generate ID of a single item
- re-generate IDs for all items within a given parent scope
- re-generate IDs for all items of a given type
- the web service endpoints output a tab separated old->new mapping
which can be imported into the front-end SQL db to ensure it returns
301 moved permanently where appropriate
This isn't intended just to fix mistakes. In Eddy they seem to change
the identifier fields much more then I expected which means the hierarchical
identifier gets a bit broken! It is also useful for fixing mistakes.

Tweak slugification algorithm and add ID regeneration tools.

---

ehri-frames/src/main/java/eu/ehri/project/acl/AclManager.java
ehri-frames/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-frames/src/main/java/eu/ehri/project/persistence/utils/BundleUtils.java
ehri-frames/src/test/java/eu/ehri/project/views/AclViewsTest.java

If a user has UPDATE and CREATE permissions on a given content type it was possible to revoke one or the other, but not both. This is because given an empty set of permissions we just ignored that type, instead of revoking all permissions.
The perils of an over-complicated permission system.
Additional cleanups and reformatting included due to bad SCM control.

Fix bug with revoking all permissions on a given content type. Fixes #101

---

checkstyle.xml
java.header

Add a checkstyle module `Header` to make sure eventually all source files have a reference to the EUPL (as required by #103). The header is defined in `java.header`, but the rule ignores line 2 as the copyright holder is undetermined/dependent on the author(s) of the file.

Make checkstyle check for licence header in java files

---

ehri-importers/src/test/resources/logback-test.xml

This is so the CI system doesn't use the default, which is set to debug and this produces a stupendous amount of information.

Add a default logback-test.xml

---

ehri-frames/src/main/java/eu/ehri/project/models/annotations/Fetch.java

Perhaps unsurprisingly, this seems to cause some nasty behaviour when
serializing lots of links which are deeply nested. Rollback until a
better fix can be devised.
Better fix on the way.

Revert "Increased default/max recursive traversals to deal with deeply nested collections"

---

assembly/pom.xml
ehri-cmdline/pom.xml
ehri-definitions/pom.xml
ehri-extension-sparql/pom.xml
ehri-extension/pom.xml
ehri-frames/pom.xml
ehri-frames/src/main/java/eu/ehri/project/models/Annotation.java
ehri-frames/src/main/java/eu/ehri/project/models/Link.java
ehri-frames/src/main/java/eu/ehri/project/models/PermissionGrant.java
ehri-frames/src/main/java/eu/ehri/project/models/VirtualUnit.java
ehri-frames/src/main/java/eu/ehri/project/models/annotations/Fetch.java
ehri-frames/src/main/java/eu/ehri/project/models/base/AccessibleEntity.java
ehri-frames/src/main/java/eu/ehri/project/models/base/Description.java
ehri-frames/src/main/java/eu/ehri/project/models/base/Promotable.java
ehri-frames/src/main/java/eu/ehri/project/models/events/SystemEvent.java
ehri-frames/src/main/java/eu/ehri/project/models/events/Version.java
ehri-frames/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-frames/src/main/java/eu/ehri/project/persistence/Serializer.java
ehri-frames/src/main/java/eu/ehri/project/persistence/utils/BundlePath.java
ehri-frames/src/main/java/eu/ehri/project/persistence/utils/BundleUtils.java
ehri-frames/src/main/java/eu/ehri/project/views/Query.java
ehri-frames/src/test/java/eu/ehri/project/persistence/BundleTest.java
ehri-frames/src/test/java/eu/ehri/project/persistence/SerializerTest.java
ehri-frames/src/test/java/eu/ehri/project/persistence/utils/BundleUtilsTest.java
ehri-frames/src/test/resources/fixtures/testdata.yaml
ehri-importers/pom.xml
pom.xml

Add a way to limit the relative depth of traversal for individual
serialized relationships. Currently, fetching auto-serialized rels
recurses until a global default depth is reached. This can lead to
some pathological cases with higher depth levels, however, as well
as resulting in a lot of unnecessary data being transferred. A good
example of this is targets for links and notes: we only need the top-
level item itself in 99.9% of cases, not the whole tree and full context.
With higher depth levels, fetching all links for an item could lead to an
enormous amount of data being transferred, most of it unnecessary.
This problem is particularly acute when there's an erroneous relationship
loop, such as with #115. These loops shouldn't happen, but neither should
their occurence break things. …

Improvements to frame serialization config to fix #114.

---

ehri-extension/src/main/java/eu/ehri/extension/AdminResource.java
ehri-extension/src/test/java/eu/ehri/extension/test/AdminRestClientTest.java
ehri-frames/src/main/java/eu/ehri/project/models/Country.java
ehri-frames/src/main/java/eu/ehri/project/models/DocumentaryUnit.java
ehri-frames/src/main/java/eu/ehri/project/models/Group.java
ehri-frames/src/main/java/eu/ehri/project/models/Repository.java
ehri-frames/src/main/java/eu/ehri/project/models/UserProfile.java
ehri-frames/src/main/java/eu/ehri/project/models/VirtualUnit.java
ehri-frames/src/main/java/eu/ehri/project/models/annotations/Meta.java
ehri-frames/src/main/java/eu/ehri/project/models/base/Watchable.java
ehri-frames/src/main/java/eu/ehri/project/models/cvoc/AuthoritativeSet.java
ehri-frames/src/main/java/eu/ehri/project/models/cvoc/Concept.java
ehri-frames/src/main/java/eu/ehri/project/models/events/SystemEvent.java
ehri-frames/src/main/java/eu/ehri/project/models/utils/ClassUtils.java
ehri-frames/src/main/java/eu/ehri/project/persistence/Serializer.java
ehri-frames/src/test/java/eu/ehri/project/models/CountryTest.java
ehri-frames/src/test/java/eu/ehri/project/models/UserProfileTest.java

Previously, the number of child items an `ItemHolder` has was cached in
a property. Due to the limitations of Frames, the code to do this had
to be repeated in a very ugly way. Also, while I'm not sure how much slower,
if at all, counting relationships is compared to looking up a property is,
but I doubt it's worth the additional complexity.
Also, with the caching there was inevitably issues with invalidation,
which turned out to be an actual problem.
This patch introduces a `@Meta(name)` annotation that can be affixed
to frame methods that return scalar values, which will be automatically
included in the bundle meta section.
Testing performance of full-graph serialization show neglibable performance
difference for the same functionality. Fetching watched count, however, adds
a small …

Improvements to serialization of metadata values and various model cleanups

---

ehri-frames/src/main/java/eu/ehri/project/models/base/ItemHolder.java

This prevented the frontend being able to discern the number of child items.

Remove prefix from child count name, now it's not used for cache purposes

---

Dockerfile
build-docker.sh
run-docker.sh

I'm sure there's a lot wrong with this but it appears to work.
Would be nice to set up a automatic build to Docker hub but I don't know how to trigger the Maven build prior to building the Dockerfile.
This creates a running DB with the graph initialized, but without any users. It might be nice to be able to add an admin user via some ENV property or something.

Add inexpertly-configured stuff to build/run a docker image

---

ehri-extension/src/test/java/eu/ehri/extension/test/helpers/ServerRunner.java

This won't affect runtime behaviour, but should make testing the rest client a bit more repeatable, especially when we fire lots of requests at the server, some of which occasionally fail at the moment.
In any case, this problem should go away with Neo4j 2, which due to read transactions doesn't have index/store inconsistencies nearly as much.

In the test server, check iterated elements for deletions in the current TX

---

ehri-frames/src/test/java/eu/ehri/project/persistence/BundleDAOTest.java
ehri-frames/src/test/java/eu/ehri/project/persistence/SerializerTest.java

These tests will break if/when we update for Neo4j 2.2.x, but they're fragile now since iteration order is not guaranteed.

Fix some iteration order sensitive tests

---

ehri-extension/src/main/java/eu/ehri/extension/AdminResource.java
ehri-extension/src/test/java/eu/ehri/extension/test/AdminRestClientTest.java
ehri-frames/src/main/java/eu/ehri/project/acl/AclManager.java
ehri-frames/src/main/java/eu/ehri/project/acl/wrapper/AclEdge.java
ehri-frames/src/main/java/eu/ehri/project/acl/wrapper/AclEdgeIterable.java
ehri-frames/src/main/java/eu/ehri/project/acl/wrapper/AclElement.java
ehri-frames/src/main/java/eu/ehri/project/acl/wrapper/AclGraph.java
ehri-frames/src/main/java/eu/ehri/project/acl/wrapper/AclVertex.java
ehri-frames/src/main/java/eu/ehri/project/acl/wrapper/AclVertexIterable.java
ehri-frames/src/main/java/eu/ehri/project/core/impl/neo4j/Neo4j2Graph.java
ehri-frames/src/test/java/eu/ehri/project/acl/wrapper/AclGraphTest.java

The ACL graph is a wrapper that, given an accessor (user/group), hides vertices to which that accessor does not have access.
Currently it is only used in the GraphSON export, providing a means to export the full graph whilst excluding restricted-visibility nodes.

Add ACL graph wrapper

---

ehri-extension/src/main/java/eu/ehri/extension/AbstractRestResource.java
ehri-extension/src/main/java/eu/ehri/extension/SystemEventResource.java
ehri-frames/src/main/java/eu/ehri/project/views/EventViews.java

At the cost of making these things more "stringly-typed" we now convert from strings in the builder. This is because trying to do it generically did not work (and nor did the previous Jersey params version).

Change the way event type/show/item-class params are deserialized.

---

assembly/pom.xml
ehri-cmdline/pom.xml
ehri-definitions/pom.xml
ehri-definitions/src/main/java/eu/ehri/project/definitions/Entities.java
ehri-extension-sparql/pom.xml
ehri-extension/pom.xml
ehri-extension/src/main/java/eu/ehri/extension/AbstractRestResource.java
ehri-extension/src/main/java/eu/ehri/extension/AdminResource.java
ehri-extension/src/main/java/eu/ehri/extension/ToolsResource.java
ehri-extension/src/test/java/eu/ehri/extension/test/AdminRestClientTest.java
ehri-frames/pom.xml
ehri-frames/src/main/java/eu/ehri/project/core/GraphManager.java
ehri-frames/src/main/java/eu/ehri/project/core/impl/BlueprintsGraphManager.java
ehri-frames/src/main/java/eu/ehri/project/models/EntityClass.java
ehri-frames/src/main/java/eu/ehri/project/models/events/EventLink.java
ehri-frames/src/main/java/eu/ehri/project/models/events/SystemEvent.java
ehri-frames/src/main/java/eu/ehri/project/persistence/ActionManager.java
ehri-frames/src/main/java/eu/ehri/project/tools/JsonDataExporter.java
ehri-importers/pom.xml
pom.xml

We don't actually export RDF directly (yet) but the added JSON data export format is easier to transform/stream an entire graph into RDF than GraphSON or bundles, since it is vertex-based and includes both id and type of outgoing relationship target vertices.
The only vertices in the graph which _didn't_ have __ID__ and __ISA__ properties before were event links. This has now been changed so these can be exported with the same transformations as other nodes. A helper has been added to create ID and ISA on event links which don't currently have them.
- add new `eventLink` type
- set an entity type and ID on event link nodes in the ActionManager
- add a WS helper to set these were they don't exist
- add a data exporter better suited to RDF translation
- increase version to 0.10.2-SNAPSHOT, …

Changes to facilite more RDF-friendly data export.

---

assembly/pom.xml
ehri-cmdline/pom.xml
ehri-definitions/pom.xml
ehri-extension-sparql/pom.xml
ehri-extension/pom.xml
ehri-frames/pom.xml
ehri-importers/pom.xml
pom.xml

Bump version to 0.10.3-SNAPSHOT.
Fixes #169.

URLdecode log message headers.

---

assembly/pom.xml
ehri-cmdline/pom.xml
ehri-definitions/pom.xml
ehri-extension-sparql/pom.xml
ehri-extension/pom.xml
ehri-extension/src/main/java/eu/ehri/extension/AbstractRestResource.java
ehri-extension/src/main/java/eu/ehri/extension/ImportResource.java
ehri-frames/pom.xml
ehri-importers/pom.xml
fabfile.py
pom.xml
scripts/import-large-batch.sh
src/site/markdown/install.md

Calling the current user header "Authorization" conflicts with Neo4j's
basic auth DBMS server security, and is also a misnomer since it's just
a marker we always trust. It's now renamed `X-User`.
Additionally, rename the `logMessage` header to `X-LogMessage` for
consistency.
Since this breaks behaviour on the front end, bump version.

Rename some web service headers. Fixes #172.

---

assembly/pom.xml
ehri-cmdline/pom.xml
ehri-definitions/pom.xml
ehri-extension-sparql/pom.xml
ehri-extension/pom.xml
ehri-extension/src/main/java/eu/ehri/extension/AbstractAccessibleEntityResource.java
ehri-extension/src/main/java/eu/ehri/extension/AbstractRestResource.java
ehri-extension/src/main/java/eu/ehri/extension/AnnotationResource.java
ehri-extension/src/main/java/eu/ehri/extension/AuthoritativeSetResource.java
ehri-extension/src/main/java/eu/ehri/extension/ContentTypeResource.java
ehri-extension/src/main/java/eu/ehri/extension/CountryResource.java
ehri-extension/src/main/java/eu/ehri/extension/CvocConceptResource.java
ehri-extension/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java
ehri-extension/src/main/java/eu/ehri/extension/GroupResource.java
ehri-extension/src/main/java/eu/ehri/extension/HistoricalAgentResource.java
ehri-extension/src/main/java/eu/ehri/extension/LinkResource.java
ehri-extension/src/main/java/eu/ehri/extension/RepositoryResource.java
ehri-extension/src/main/java/eu/ehri/extension/SystemEventResource.java
ehri-extension/src/main/java/eu/ehri/extension/UserProfileResource.java
ehri-extension/src/main/java/eu/ehri/extension/VirtualUnitResource.java
ehri-extension/src/main/java/eu/ehri/extension/VocabularyResource.java
ehri-extension/src/main/java/eu/ehri/extension/base/ListResource.java
ehri-extension/src/main/java/eu/ehri/extension/base/ParentResource.java
ehri-extension/src/test/java/eu/ehri/extension/test/BaseRestClientTest.java
ehri-extension/src/test/java/eu/ehri/extension/test/SystemEventRestClientTest.java
ehri-frames/pom.xml
ehri-importers/pom.xml
pom.xml

- remove `/list` from list endpoints (now just using the resource name)
- remove all `/count` endpoints (can be done using `HEAD` requests on list endpoints)
- upgrade Neo4j version
- bump version to 0.11.0
Fix an existing (unnoticed) issue where `HEAD` requests would like a transaction on streaming endpoints.

Web service API refactoring (part 1)

---

ehri-frames/src/main/java/eu/ehri/project/acl/AclManager.java
ehri-frames/src/main/java/eu/ehri/project/persistence/BundleDAO.java
ehri-frames/src/main/java/eu/ehri/project/persistence/BundleValidator.java
ehri-frames/src/main/java/eu/ehri/project/views/AnnotationViews.java
ehri-frames/src/main/java/eu/ehri/project/views/Query.java
ehri-frames/src/main/java/eu/ehri/project/views/QueryUtils.java
ehri-frames/src/test/java/eu/ehri/project/views/QueryTest.java
ehri-importers/src/main/java/eu/ehri/project/importers/AbstractImporter.java

Addesses #82. Some additional test cleanup.

Remove iterables as argument types when not expecting lazy data.

---

ehri-extension/src/main/java/eu/ehri/extension/VocabularyResource.java
ehri-importers/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java
ehri-importers/src/test/java/eu/ehri/project/exporters/cvoc/JenaSkosExporterTest.java

Fixes #190.
Also, add more test assertions and fix a default value on the web service endpoint that caused Enunciate to crash.

Fix incorrect use of graph local/global IDs in SKOS export.

---

assembly/src/main/assembly/unix.xml

It turns out that we did need the jettison dependency for GraphSON export support. Whoops.

Fix graphson export.

---

ehri-core/src/main/java/eu/ehri/project/acl/AclManager.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclEdgeIterable.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclGraph.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclVertex.java
ehri-core/src/test/java/eu/ehri/project/acl/wrapper/AclGraphTest.java

Logically, it should not have been possible to see edges that were connected to invisible nodes. However, because we weren't filtering edges based on start/end visibility, GraphSON dumps has inconsistent node/edge counts.
Fixes #216.

Fix loading of ACL-filtered exported graphs.

---

ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclEdge.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclEdgeIterable.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclElement.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclGraph.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclVertex.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclVertexIterable.java
ehri-core/src/main/java/eu/ehri/project/views/EventViews.java
ehri-core/src/test/java/eu/ehri/project/acl/wrapper/AclGraphTest.java

Additionally, provide better toStrings and fix an erroneous test.

More fixes to prevent the ACL graph leaking non-ACL-aware primitives.

---

assembly/src/main/assembly/unix.xml
ehri-io/pom.xml
ehri-io/src/main/java/eu/ehri/project/importers/managers/CsvImportManager.java
ehri-io/src/test/java/eu/ehri/project/importers/PersonalitiesImporterTest.java
ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java

Since we're already using Jackson extensively this makes sense, also:
- the reader API is a bit nicer and more full-features
- quote when writing can be strict on-demand (not just on or off)
Additional small test cleanups.

Switch from OpenCSV to Jackson Dataformat CSV.

---

ehri-core/src/main/java/eu/ehri/project/models/AccessPoint.java
ehri-core/src/main/java/eu/ehri/project/models/DatePeriod.java
ehri-core/src/main/java/eu/ehri/project/models/DocumentaryUnit.java
ehri-core/src/main/java/eu/ehri/project/models/PermissionGrant.java
ehri-core/src/main/java/eu/ehri/project/models/Repository.java
ehri-core/src/main/java/eu/ehri/project/models/annotations/InverseOf.java
ehri-core/src/main/java/eu/ehri/project/models/annotations/Mandatory.java
ehri-core/src/main/java/eu/ehri/project/models/base/Description.java
ehri-core/src/main/java/eu/ehri/project/models/base/Entity.java
ehri-core/src/main/java/eu/ehri/project/models/cvoc/AuthoritativeItem.java
ehri-core/src/main/java/eu/ehri/project/models/cvoc/Concept.java
ehri-core/src/main/java/eu/ehri/project/models/cvoc/ConceptDescription.java
ehri-core/src/main/java/eu/ehri/project/models/events/SystemEvent.java
ehri-core/src/main/java/eu/ehri/project/models/events/SystemEventQueue.java
ehri-core/src/main/java/eu/ehri/project/models/idgen/IdGeneratorUtils.java
ehri-core/src/main/java/eu/ehri/project/models/utils/ClassUtils.java
ehri-core/src/test/java/eu/ehri/project/models/CvocConceptTest.java
ehri-core/src/test/java/eu/ehri/project/models/DocumentaryUnitTest.java
ehri-core/src/test/java/eu/ehri/project/models/events/SystemEventQueueTest.java
ehri-core/src/test/java/eu/ehri/project/models/events/SystemEventTest.java
ehri-io/src/main/java/eu/ehri/project/exporters/cvoc/SchemaExporter.java
ehri-io/src/main/java/eu/ehri/project/importers/AbstractImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/MapImporter.java
ehri-io/src/test/java/eu/ehri/project/exporters/cvoc/SchemaExporterTest.java
ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractRestResource.java

This only concerns the so-called 'functional' schema, i.e. mandatory properties and relationships.
Various additional tweaks to the model schema and elsewhere.

Add a class that can export the model schema as RDFS/Owl triples.

---

ehri-core/pom.xml
ehri-core/src/main/java/eu/ehri/project/models/AccessPoint.java
ehri-core/src/main/java/eu/ehri/project/models/Annotation.java
ehri-core/src/main/java/eu/ehri/project/models/UserProfile.java
ehri-core/src/main/java/eu/ehri/project/models/base/AbstractUnit.java
ehri-core/src/main/java/eu/ehri/project/models/base/Accessible.java
ehri-core/src/main/java/eu/ehri/project/models/base/Annotator.java
ehri-core/src/main/java/eu/ehri/project/models/base/Described.java
ehri-core/src/main/java/eu/ehri/project/models/base/Linkable.java
ehri-core/src/main/java/eu/ehri/project/views/AnnotationViews.java
ehri-core/src/main/java/eu/ehri/project/views/LinkViews.java
ehri-core/src/main/java/eu/ehri/project/views/Query.java
ehri-core/src/main/java/eu/ehri/project/views/QueryUtils.java
ehri-core/src/test/java/eu/ehri/project/models/AnnotationTest.java
ehri-core/src/test/java/eu/ehri/project/views/AnnotationViewsTest.java
ehri-core/src/test/java/eu/ehri/project/views/LinkViewsTest.java
ehri-core/src/test/java/eu/ehri/project/views/QueryTest.java
ehri-core/src/test/java/eu/ehri/project/views/QueryUtilsTest.java
ehri-core/src/test/resources/fixtures/testdata.yaml
ehri-io/pom.xml
ehri-ws-sparql/pom.xml
ehri-ws/pom.xml
ehri-ws/src/main/java/eu/ehri/extension/AnnotationResource.java
ehri-ws/src/main/java/eu/ehri/extension/LinkResource.java

- rationalise models, removing `Annotator` base class
- remove 'advanced' `Query` functionality, which was unused, fragile, and confusing

More cleanups

---

ehri-cli/src/main/java/eu/ehri/project/commands/ListEntities.java
ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-core/src/main/java/eu/ehri/project/persistence/DataConverter.java
ehri-core/src/main/java/eu/ehri/project/persistence/Serializer.java
ehri-core/src/test/java/eu/ehri/project/persistence/DataConverterTest.java
ehri-ws/src/main/java/eu/ehri/extension/AdminResource.java
ehri-ws/src/main/java/eu/ehri/extension/AnnotationResource.java
ehri-ws/src/main/java/eu/ehri/extension/AuthoritativeSetResource.java
ehri-ws/src/main/java/eu/ehri/extension/ContentTypeResource.java
ehri-ws/src/main/java/eu/ehri/extension/CountryResource.java
ehri-ws/src/main/java/eu/ehri/extension/CvocConceptResource.java
ehri-ws/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java
ehri-ws/src/main/java/eu/ehri/extension/GenericResource.java
ehri-ws/src/main/java/eu/ehri/extension/GroupResource.java
ehri-ws/src/main/java/eu/ehri/extension/HistoricalAgentResource.java
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/main/java/eu/ehri/extension/LinkResource.java
ehri-ws/src/main/java/eu/ehri/extension/PermissionGrantResource.java
ehri-ws/src/main/java/eu/ehri/extension/PermissionsResource.java
ehri-ws/src/main/java/eu/ehri/extension/RepositoryResource.java
ehri-ws/src/main/java/eu/ehri/extension/SystemEventResource.java
ehri-ws/src/main/java/eu/ehri/extension/UserProfileResource.java
ehri-ws/src/main/java/eu/ehri/extension/VirtualUnitResource.java
ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractRestResource.java

This alternative serialization format has not been used, and has always been a second-class citizen. Removing it simplifies the serialization code.

Strip out all bundle XML support.

---

ehri-io/src/main/java/eu/ehri/project/exporters/ead/Ead2002Exporter.java
ehri-io/src/main/resources/allowedNodeProperties.csv
ehri-io/src/main/resources/icaatom.properties
ehri-io/src/test/java/eu/ehri/project/exporters/ead/Ead2002ExporterTest.java

This field maps on import and export to `separatedUnitsOfDescription`.

Add better I/O mappings for EAD separatedmaterial

---

ehri-io/src/main/java/eu/ehri/project/importers/MapImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/SaxImportManager.java
ehri-io/src/test/java/eu/ehri/project/importers/MapImporterTest.java

- Make the date normalisation functions non-static since they use non-reentrant parsers internally. Make these parsers instance fields.
- Don't catch and re-throw illegal argument exceptions in the Sax import manager since it eats too many errors that could be usefully passed to the client

Small changes to date normalisation and error handling.

---

ehri-io/src/main/java/eu/ehri/project/exporters/eac/Eac2010Exporter.java
ehri-io/src/main/java/eu/ehri/project/exporters/eag/Eag2012Exporter.java
ehri-io/src/main/java/eu/ehri/project/importers/base/MapImporter.java
ehri-io/src/main/resources/eag.properties
ehri-io/src/main/resources/wienerlib.properties
ehri-io/src/test/resources/exportdata.yaml

In some cases these have to be renamed in the DB via Cypher:
```cypher
MATCH (me:MaintenanceEvent)
WHERE me.`maintenanceEvent/date` IS NOT NULL
SET me.date = me.`maintenanceEvent/date`
REMOVE me.`maintenanceEvent/date`
RETURN COUNT(me)
```
```cypher
MATCH (me:MaintenanceEvent)
WHERE me.`maintenanceEvent/source` IS NOT NULL
SET me.source = me.`maintenanceEvent/source`
REMOVE me.`maintenanceEvent/source`
RETURN COUNT(me)
```
```cypher
MATCH (me:MaintenanceEvent)
WHERE me.type IS NOT NULL
SET me.eventType = me.type
REMOVE me.type
RETURN COUNT(me)
```

Correct some badly-named maintenance event properties

---

ehri-io/src/main/resources/simpledc20021212.xsd
ehri-io/src/main/resources/xml.xsd
ehri-io/src/test/java/eu/ehri/project/exporters/test/LocalResourceResolver.java
ehri-io/src/test/java/eu/ehri/project/exporters/test/XmlExporterTest.java

This should make sure that everything that should be resolved in an XML file (e.g. the xlink schema) is present as a local resource.
Fixes #242.

Attempt to prevent network access for XML-schema validation tests.

---

ehri-ws/src/main/java/eu/ehri/extension/AdminResource.java
ehri-ws/src/main/java/eu/ehri/extension/AnnotationResource.java
ehri-ws/src/main/java/eu/ehri/extension/AuthoritativeSetResource.java
ehri-ws/src/main/java/eu/ehri/extension/CountryResource.java
ehri-ws/src/main/java/eu/ehri/extension/CvocConceptResource.java
ehri-ws/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java
ehri-ws/src/main/java/eu/ehri/extension/GenericResource.java
ehri-ws/src/main/java/eu/ehri/extension/GroupResource.java
ehri-ws/src/main/java/eu/ehri/extension/HistoricalAgentResource.java
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/main/java/eu/ehri/extension/LinkResource.java
ehri-ws/src/main/java/eu/ehri/extension/PermissionGrantResource.java
ehri-ws/src/main/java/eu/ehri/extension/PermissionsResource.java
ehri-ws/src/main/java/eu/ehri/extension/RepositoryResource.java
ehri-ws/src/main/java/eu/ehri/extension/SystemEventResource.java
ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
ehri-ws/src/main/java/eu/ehri/extension/UserProfileResource.java
ehri-ws/src/main/java/eu/ehri/extension/VirtualUnitResource.java
ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractAccessibleResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractResource.java

Streaming responses now run in a different transaction to the body of the request. This is less _transactional_, but much simpler, and doesn't have problems with edge cases like HEAD requests where Jersey skips the body altogether.

Refactor web service transactions in streaming responses.

---

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java
ehri-ws-graphql/src/test/resources/testquery.graphql

We always use `Entity` as the base type and do frame casting as necessary.

Squash more data fetching errors

---

ehri-core/src/main/java/eu/ehri/project/models/utils/ClassUtils.java
ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-core/src/main/java/eu/ehri/project/persistence/BundleValidator.java
ehri-core/src/main/java/eu/ehri/project/persistence/ErrorSet.java
ehri-core/src/main/java/eu/ehri/project/persistence/NestableData.java
ehri-core/src/main/java/eu/ehri/project/persistence/messages.properties
ehri-core/src/main/java/eu/ehri/project/persistence/utils/DataUtils.java
ehri-core/src/main/java/eu/ehri/project/persistence/utils/NestableDataPath.java
ehri-core/src/test/java/eu/ehri/project/api/EventsApiTest.java
ehri-core/src/test/java/eu/ehri/project/models/utils/ClassUtilsTest.java
ehri-core/src/test/java/eu/ehri/project/persistence/BundleManagerTest.java
ehri-core/src/test/java/eu/ehri/project/persistence/BundleTest.java
ehri-core/src/test/java/eu/ehri/project/persistence/BundleValidatorTest.java
ehri-core/src/test/java/eu/ehri/project/persistence/ErrorSetTest.java
ehri-core/src/test/java/eu/ehri/project/persistence/SerializerTest.java
ehri-core/src/test/java/eu/ehri/project/persistence/utils/DataUtilsTest.java
ehri-core/src/test/java/eu/ehri/project/test/TestData.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/EadImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/IcaAtomEadImporter.java
ehri-io/src/test/java/eu/ehri/project/importers/eag/Eag2896Test.java
ehri-io/src/test/java/eu/ehri/project/importers/json/BatchOperationsTest.java
ehri-io/src/test/resources/eag-2896.xml

1. Bundle and ErrorSet now implements a NestableData interface,  and the BundleUtils (now DataUtils) can manipulate them both
2. Added input validation for Enum properties, such as access point type
3. Some test fixes related to 2.

Improvements to internal structures and validation.

---

ehri-core/src/main/java/eu/ehri/project/persistence/DataConverter.java
ehri-core/src/test/java/eu/ehri/project/test/GraphTestBase.java
ehri-io/src/main/java/eu/ehri/project/importers/base/AbstractImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/CsvImportManager.java
ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java
ehri-ws-graphql/src/test/java/eu/ehri/project/graphql/GraphQLImplTest.java
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/ImportResourceResourceClientTest.java

Eliminate a GraphQL hotspot by loading various (resource-configured) field definitions statically, rather than at schema instantiation.
Various other cleanups and deprecation fixes.

GraphQL optimisations and cleanup.

---

ehri-core/src/main/java/eu/ehri/project/models/Link.java
ehri-core/src/test/java/eu/ehri/project/models/LinkTest.java
ehri-core/src/test/resources/fixtures/testdata.yaml
ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/ToolsResourceClientTest.java

This is useful for some of the data cleanup we're doing with concepts.
Also fix indentation in the fixture file.

Add a utility function for remapping link targets from one item to another

---

ehri-core/src/main/java/eu/ehri/project/api/QueryApi.java
ehri-ws-oaipmh/src/main/java/eu/ehri/extension/OaiPmhResource.java
ehri-ws-oaipmh/src/main/java/eu/ehri/project/oaipmh/OaiPmhData.java
ehri-ws-oaipmh/src/main/java/eu/ehri/project/oaipmh/OaiPmhExporter.java
ehri-ws-oaipmh/src/main/java/eu/ehri/project/oaipmh/OaiPmhState.java
ehri-ws-oaipmh/src/main/resources/reference.conf
ehri-ws-oaipmh/src/test/java/eu/ehri/extension/test/OaiPmhResourceClientTest.java

Both X-Limit and X-Stream can be given as headers, but the latterwill override the former (disabling paging).
Adjust code for listSets so that it uses a Page, rather than a raw stream.

Make limit/stream behaviour consistent with the GraphQL API.

---

ehri-cypher/src/main/java/eu/ehri/project/cypher/Procedures.java
ehri-cypher/src/test/java/eu/ehri/project/cypher/ProceduresTest.java

This is useful since (unfortunately) we have some properties that can be either single or array values.

Add a procedure to coerce property values to a list.

---

ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-core/src/main/java/eu/ehri/project/tools/FindReplace.java
ehri-core/src/test/java/eu/ehri/project/persistence/BundleTest.java
ehri-core/src/test/java/eu/ehri/project/tools/FindReplaceTest.java
ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/ToolsResourceClientTest.java

This is a less blunt alternative to going behind-the-scenes of the DB and doing find/replace with Cypher. It also has some ways to prevent accidental mis-use, such as only doing a certain number of items at a time.

Add a find-and-replace tool which handles updating the audit log.

---

ehri-core/src/main/java/eu/ehri/project/tools/FindReplace.java
ehri-core/src/test/java/eu/ehri/project/tools/FindReplaceTest.java
ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java

Now includes the sub-type id and the current text in which a match was found. Also, does not require a log message with no replacement value.

Add more info to find/replace output.

---

ehri-core/src/main/java/eu/ehri/project/models/cvoc/Concept.java
ehri-core/src/main/java/eu/ehri/project/models/utils/JavaHandlerUtils.java
ehri-core/src/test/java/eu/ehri/project/models/cvoc/ConceptTest.java
ehri-core/src/test/resources/fixtures/testdata.yaml
ehri-io/pom.xml
ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/AbstractSkosTest.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/JenaSkosImporterTest.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/Wp2KeywordsTest.java
ehri-io/src/test/java/eu/ehri/project/importers/ead/IcaAtomMultiLeveledTest.java
ehri-io/src/test/resources/cvoc/simple-xl.n3
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/ToolsResourceClientTest.java

This is a bit of a hack: adds RDFS subPropertyOf relations for `skosxl:{pref,alt,hidden}Label` to `skos:{pref,alt,hidden}Label` and looks up the values depending on whether the object is a literal or not.

Add tentative support for SKOS-XL labels.

---

ehri-io/src/main/java/eu/ehri/project/importers/ImportLog.java
ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java
ehri-io/src/test/resources/cvoc/simple-xl.n3
ehri-io/src/test/resources/cvoc/simple.n3

In cases where values are reified, e.g. labels or definition nodes, the values can possibly be missing. Handle this case without crashing with a NPE.

At the expense of more horrid code, make SKOS import more robust.

---

ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/ToolsResourceClientTest.java

This prevents 414 (url too long) errors with lots of items.

Make renegerating specific IDs more flexible by accepting JSON/CSV.

---

ehri-io/src/main/java/eu/ehri/project/exporters/ead/Ead2002Exporter.java
ehri-io/src/test/java/eu/ehri/project/exporters/ead/Ead2002ExporterTest.java

This should improve round trip export/ingest fidelity (though still much work to do on that score.)

Add source and authfilenumber references to EAD access points.

---

ehri-io/src/main/java/eu/ehri/project/importers/base/SaxXmlHandler.java

This prevents e.g. spaces in attributes causing problems.

Escape attribute values that are used to qualify ingest mappings.

---

ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/EventsSkosImporterTest.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/GhettosImporterTest.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/GhettosImporterV20140831Test.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/JenaSkosImporterTest.java
ehri-io/src/test/java/eu/ehri/project/importers/cvoc/Wp2PlacesImporterTest.java

Migration script:
```
MATCH (c:CvocConcept)<-[:describes]-(cd:CvocConceptDescription)
WHERE exists(cd.longitude) OR
exists(cd.latitude) OR 
exists(cd.url) OR 
exists(cd.seeAlso)
SET 
c.longitude = cd.longitude,
c.latitude = cd.latitude,
c.url = cd.url,
c.seeAlso = cd.seeAlso
REMOVE 
cd.longitude, cd.latitude, cd.url, cd.seeAlso
RETURN COUNT(c)
```

Move non-language-specific properties from concept description to item.

---

ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-core/src/main/java/eu/ehri/project/persistence/BundleManager.java
ehri-core/src/test/java/eu/ehri/project/persistence/BundleTest.java
ehri-io/src/main/java/eu/ehri/project/importers/json/BatchOperations.java
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/main/java/eu/ehri/extension/RepositoryResource.java

- fix an issue with bundle updating that meant non-dependent data
would break idempotency checks
- add a POST /{id}/list endpoint to the repository resource for
importing sets of doc units. Ideally this functionality would
be generic somehow or able to be shared across multiple resources
that have child items.

Allow importing multiple doc units via JSON.

---

ehri-ws/src/main/java/eu/ehri/extension/AuthoritativeSetResource.java
ehri-ws/src/main/java/eu/ehri/extension/CountryResource.java
ehri-ws/src/main/java/eu/ehri/extension/CvocConceptResource.java
ehri-ws/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java
ehri-ws/src/main/java/eu/ehri/extension/GenericResource.java
ehri-ws/src/main/java/eu/ehri/extension/GroupResource.java
ehri-ws/src/main/java/eu/ehri/extension/PermissionsResource.java
ehri-ws/src/main/java/eu/ehri/extension/RepositoryResource.java
ehri-ws/src/main/java/eu/ehri/extension/SystemEventResource.java
ehri-ws/src/main/java/eu/ehri/extension/UserProfileResource.java
ehri-ws/src/main/java/eu/ehri/extension/VirtualUnitResource.java
ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractAccessibleResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractResource.java

This means we don't create the iterator in a different transaction to the one it will (potentially) be run under, which breaks in Neo4j 3.1+.
Fixes #349.

Use a thunk for streaming responses instead of the iterator itself.

---

ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/eac/EacImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/EadImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/links/LinkResolver.java
ehri-io/src/main/java/eu/ehri/project/importers/util/ImportHelpers.java
ehri-io/src/main/resources/reference.conf
ehri-io/src/test/java/eu/ehri/project/importers/links/LinkResolverTest.java
ehri-io/src/test/resources/fixtures/link-resolver.yaml

- Extracted logic into a more testable single class
- Made behaviour idempotent on update, so resolution is no longer
just run if the item is newly-created
- Extracted some magic strings to config

Refactor ingest-time link resolution.

---

ehri-ws-graphql/src/main/java/eu/ehri/extension/GraphQLResource.java
ehri-ws-graphql/src/test/java/eu/ehri/extension/test/GraphQLResourceClientTest.java
ehri-ws-graphql/src/test/java/eu/ehri/project/graphql/StreamingGraphQLTest.java
ehri-ws-graphql/src/test/resources/testquery-connection.graphql

We have to reinitialise the schema after validation in order that
iterables run in the right TX, otherwise they yield nothing.
This could be better.
Fixes #370.

Not-especially satisfactory fix for broken streaming.

---

ehri-core/pom.xml
ehri-core/src/main/java/eu/ehri/project/api/impl/EventsApiImpl.java
ehri-core/src/main/java/eu/ehri/project/api/impl/QueryApiImpl.java
ehri-core/src/main/java/eu/ehri/project/core/impl/Neo4jGraphManager.java
ehri-core/src/main/java/eu/ehri/project/core/impl/neo4j/Neo4j2Graph.java
ehri-core/src/test/java/eu/ehri/project/core/GraphManagerTest.java

- Add additional getVerticesByQuery method to the
Neo4j2Graph wrapper
- Add an index on all (managed) properties, not just
mandatory ones
- Some additional tweaks to Query classes

Prepare for more index-based querying via Cypher

---

ehri-core/src/test/java/eu/ehri/project/core/GraphManagerTest.java
ehri-core/src/test/java/eu/ehri/project/core/impl/Neo4jGraphManagerTest.java
ehri-core/src/test/java/eu/ehri/project/test/GraphTestBase.java

This fixes test issues with Neo4j 3.3.0.

Ensure temp test DBs are always closed and don't contend for the lock file

---

ehri-cli/src/main/java/eu/ehri/project/commands/EadImport.java
ehri-cli/src/main/java/eu/ehri/project/commands/GraphSON.java
ehri-cli/src/main/java/eu/ehri/project/commands/ImportCommand.java
ehri-cli/src/main/java/eu/ehri/project/commands/ImportCsvCommand.java
ehri-core/src/main/java/eu/ehri/project/acl/AccessorPermissions.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclEdgeIterable.java
ehri-core/src/main/java/eu/ehri/project/acl/wrapper/AclVertexIterable.java
ehri-core/src/main/java/eu/ehri/project/core/impl/neo4j/Neo4j2EdgeIterable.java
ehri-core/src/main/java/eu/ehri/project/core/impl/neo4j/Neo4j2VertexIterable.java
ehri-core/src/main/java/eu/ehri/project/models/utils/UniqueAdjacencyAnnotationHandler.java
ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-core/src/main/java/eu/ehri/project/persistence/DataConverter.java
ehri-core/src/main/java/eu/ehri/project/tools/FindReplace.java
ehri-io/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java
ehri-io/src/main/java/eu/ehri/project/exporters/eac/Eac2010Exporter.java
ehri-io/src/main/java/eu/ehri/project/exporters/eag/Eag2012Exporter.java
ehri-io/src/main/java/eu/ehri/project/exporters/xml/AbstractStreamingXmlExporter.java
ehri-io/src/main/java/eu/ehri/project/importers/eac/EacHandler.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/EadHandler.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/VirtualEadHandler.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/CsvImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/SaxImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/util/ImportHelpers.java
ehri-io/src/test/java/eu/ehri/project/importers/base/AbstractImporterTest.java
ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/main/java/eu/ehri/extension/ToolsResource.java

This doesn't actually fix any of the underlying type unsoundness but fixes #44.

Type boilerplate to prevent raw types warnings.

---

ehri-io/src/main/java/eu/ehri/project/importers/ead/EadHandler.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/EadImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/util/ImportHelpers.java
ehri-io/src/test/java/eu/ehri/project/importers/ead/MissingParentUnitIdEadTest.java
ehri-io/src/test/resources/missing-parent-unitid-ead.xml

This prevents NPE on id generation.
Fixes #414

Throw a validation error if (unsaved) parent item has a missing ID

---

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java
ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/messages.properties
ehri-ws-graphql/src/test/java/eu/ehri/extension/test/GraphQLResourceClientTest.java
ehri-ws-graphql/src/test/resources/logback-test.xml
ehri-ws-graphql/src/test/resources/testquery.graphql

Henceforth should use topLevel param on documentaryUnits fieldinstead.
Fixes #368

Deprecate GraphQL topLevelDocumentaryUnits field

---

ehri-core/src/main/java/eu/ehri/project/persistence/Bundle.java
ehri-core/src/main/java/eu/ehri/project/persistence/BundleValidator.java
ehri-core/src/main/java/eu/ehri/project/persistence/messages.properties
ehri-core/src/main/java/eu/ehri/project/persistence/messages_en_GB.properties
ehri-core/src/test/java/eu/ehri/project/persistence/BundleTest.java
ehri-core/src/test/java/eu/ehri/project/persistence/BundleValidatorTest.java

This could happen if, e.g., two descriptions had the same identifier.

An another integrity check to the bundle to prevent internal dup ids

---

ehri-core/pom.xml
ehri-io/pom.xml
ehri-ws-graphql/pom.xml

Should prevent a binary incompatibility w/ some later versions of Neo4j.

Update Jackson versions

---

ehri-core/src/main/java/eu/ehri/project/api/Api.java
ehri-core/src/main/java/eu/ehri/project/api/impl/ApiImpl.java
ehri-core/src/main/java/eu/ehri/project/models/Link.java
ehri-core/src/test/java/eu/ehri/project/api/ApiLinkingTest.java
ehri-definitions/src/main/java/eu/ehri/project/definitions/Ontology.java
ehri-io/src/main/java/eu/ehri/project/importers/links/LinkResolver.java
ehri-io/src/test/java/eu/ehri/project/importers/eac/PersonalitiesV2Test.java
ehri-ws/src/main/java/eu/ehri/extension/LinkResource.java

Also some parameter renaming.
This makes e.g. copy links more useful for analysis. The implementation is backwards compatible so the source (hasLinkSource) is  *also* a target (hasLinkTarget). This is a bit redundant and requires extra checks in some places, but is better than having two incompatible types of links.

Add (optional) hasLinkSource relationship for directional links.

---

ehri-ws-oaipmh/src/main/java/eu/ehri/project/oaipmh/OaiPmhExporter.java

The YYYY means year of week, which isn't the same as year of day.

Fix small issue java time format pattern: YYYY -> u

---

ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/ImportManager.java
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/ImportResourceClientTest.java

This allows importing from URLs (e.g. in Cloud storage) in a mannerthat still gives decent file name context and does not potentially leak irrelevant (and probably temporary) URLs back to the UI if
an import fails.

Extend the import manager to accept a JSON stream of name/URL pairs.

---

ehri-io/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java

Instead of
{baseURI}{concept-ident}
it's now
{baseURI}{vocab-ident}/{concept-ident}
This allows e.g. creating the URIs recommended in D11.3 when passing in a baseURI of e.g. http://data.ehri-project.eu/vocabularies/
This only affects the fallback URI however; if the concept node already has a URI that will be preferred.

Change the generated baseURI for exported SKOS to align with recs.

---

build/pom.xml
ehri-cli/pom.xml
ehri-core/pom.xml
ehri-cypher/pom.xml
ehri-definitions/pom.xml
ehri-io/pom.xml
ehri-io/src/main/java/eu/ehri/project/importers/ImportLog.java
ehri-io/src/main/java/eu/ehri/project/importers/cvoc/JenaSkosImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/json/BatchOperations.java
ehri-io/src/main/java/eu/ehri/project/importers/links/LinkImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/CsvImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/ImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/SaxImportManager.java
ehri-io/src/test/java/eu/ehri/project/importers/ImportLogTest.java
ehri-ws-graphql/pom.xml
ehri-ws-oaipmh/pom.xml
ehri-ws/pom.xml
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/main/java/eu/ehri/extension/providers/GlobalPermissionSetProvider.java
ehri-ws/src/main/java/eu/ehri/extension/providers/JsonMessageBodyHandler.java
ehri-ws/src/main/java/eu/ehri/extension/providers/TableProvider.java
ehri-ws/src/test/java/eu/ehri/extension/test/AbstractResourceClientTest.java
ehri-ws/src/test/java/eu/ehri/extension/test/ImportResourceClientTest.java
ehri-ws/src/test/java/eu/ehri/extension/test/PermissionResourceClientTest.java
pom.xml

This is part of work to improve the traceability of imported data. Imports that come from a streamed XML body will just have "-" as the key (standing for stdin).
As part of these changes various XML dependencies were upgraded as well.

Extend import logs to contain a mapping of source -> item IDs

---

ehri-core/pom.xml

Version 29 seems to cause issues in the prod environment.

Downgrade guava to a lower but still newer-than-before version.

---

ehri-io/src/main/java/eu/ehri/project/importers/base/SaxXmlHandler.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/EadHandler.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/SaxImportManager.java

The system ID gets resolved to a local file URL, which is wrong if the source was e.g. an URL.
Other minor cleanups.

Set the public ID on the Sax parser and use this for errors

---

ehri-ws/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/DocumentaryUnitResourceClientTest.java

This also throws a 409 error in the event of collisions instead of just a 500

Improve the rename method to add a way to check for collisions

---

ehri-core/src/main/java/eu/ehri/project/api/Api.java
ehri-core/src/main/java/eu/ehri/project/api/impl/ApiImpl.java
ehri-core/src/test/java/eu/ehri/project/api/ApiCrudTest.java
ehri-core/src/test/java/eu/ehri/project/api/ApiLoggingCrudTest.java
ehri-ws/src/main/java/eu/ehri/extension/AuthoritativeSetResource.java
ehri-ws/src/main/java/eu/ehri/extension/CountryResource.java
ehri-ws/src/main/java/eu/ehri/extension/CvocConceptResource.java
ehri-ws/src/main/java/eu/ehri/extension/DocumentaryUnitResource.java
ehri-ws/src/main/java/eu/ehri/extension/RepositoryResource.java
ehri-ws/src/main/java/eu/ehri/extension/VocabularyResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractAccessibleResource.java
ehri-ws/src/main/java/eu/ehri/extension/base/ParentResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/CountryResourceClientTest.java
ehri-ws/src/test/java/eu/ehri/extension/test/DocumentaryUnitResourceClientTest.java
ehri-ws/src/test/java/eu/ehri/extension/test/VocabularyResourceClientTest.java

The `delete all` methods has been changed to a (safer) `delete children` method which requires an all=true parameter to descend the hierarchy and errors if children have child nodes of their own. This method no longer deletes the parent.
The WS method signature now matches the corresponding GET method for children.

Continue to develop bulk-deletion API, w/ changes to WS API

---

ehri-core/pom.xml

This reverts commit 73a14dd6b023edf25f710d226a71418835bb8716.
Updating Guava caused a method-not-found error, to be investigated.

Revert "Bump guava from 24.1.1-jre to 29.0-jre in /ehri-core"

---

ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java

This prevents bailing when we get e.g. a 503 error for one file

Generalise to IOException when opening a remote stream for import

---

ehri-core/pom.xml

This reverts commit 7595c7c85a5b78067ec52867488c919d3c76810a, which caused an incompatible class change error on the server.

Revert "Bump commons-compress from 1.19 to 1.21 in /ehri-core"

---

build/pom.xml
ehri-cli/pom.xml
ehri-core/pom.xml
ehri-core/src/main/java/eu/ehri/project/persistence/Mutation.java
ehri-core/src/test/java/eu/ehri/project/persistence/SerializerTest.java
ehri-core/src/test/java/eu/ehri/project/tools/LinkerTest.java
ehri-core/src/test/resources/fixtures/testdata.yaml
ehri-cypher/pom.xml
ehri-definitions/pom.xml
ehri-io/pom.xml
ehri-io/src/main/java/eu/ehri/project/importers/links/LinkImporter.java
ehri-io/src/test/java/eu/ehri/project/importers/links/LinkImporterTest.java
ehri-io/src/test/resources/fixtures/link-resolver.yaml
ehri-ws-graphql/pom.xml
ehri-ws-graphql/src/test/java/eu/ehri/extension/test/GraphQLResourceClientTest.java
ehri-ws-oaipmh/pom.xml
ehri-ws/pom.xml
ehri-ws/src/main/java/eu/ehri/extension/ImportResource.java
ehri-ws/src/test/java/eu/ehri/extension/test/ImportResourceClientTest.java
ehri-ws/src/test/java/eu/ehri/extension/test/ToolsResourceClientTest.java
pom.xml

This is able to idempotently set the link body to an access point matching the text-to-target pairing given in the provided table.
Also bumped version.

Add a coreference table importer to the import resource

---

ehri-io/src/main/resources/ead2002.properties
ehri-io/src/test/java/eu/ehri/project/importers/ead/IcaAtomEadSingleEadTest.java
ehri-io/src/test/resources/single-ead.xml

This is a bit gross, since it's kind of a misuse of the tag, but there are few other places to put an extptr that won't break existing
assumptions. :|

Add an EAD hack to extract the 'ref' field from materialspec/extptr

---

Dockerfile
pom.xml
scripts/initdb.sh

We now only run initialisation in the Docker image if there is no graph already. This makes the image useful for dev as well
as testing.

Update Neo4j to 3.5.28 and tweak the Docker init script

---

ehri-io/src/main/java/eu/ehri/project/exporters/cvoc/JenaSkosExporter.java
ehri-io/src/main/java/eu/ehri/project/importers/cvoc/SkosRDFVocabulary.java
ehri-io/src/test/java/eu/ehri/project/exporters/cvoc/JenaSkosExporterTest.java
ehri-ws/src/main/java/eu/ehri/extension/base/AbstractResource.java

This led to the actual DC properties having an auto-gen random prefix
Also re-use some existing Jena SKOS definitions

Fix an issue with incorrect DC prefix on the SKOS exporter

---

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java
ehri-ws-graphql/src/test/java/eu/ehri/project/ws/test/GraphQLResourceClientTest.java
ehri-ws-graphql/src/test/resources/testquery.graphql

Two different issues here: there was a missing data fetcher for the link and annotation targets relationship. Unrelatedly, there was a name clash which resulted in the concept type attempting to return a set of relationship items for the `related` instead of SKOS `related` concepts (very confusing I know.)

Fix fetching of link targets and Concept related items

---

ehri-io/src/main/java/eu/ehri/project/importers/ead/EadHandler.java
ehri-io/src/main/java/eu/ehri/project/importers/ead/EadImporter.java
ehri-io/src/main/java/eu/ehri/project/importers/managers/AbstractImportManager.java
ehri-io/src/test/java/eu/ehri/project/importers/ead/AnonymousCLevelTest.java
ehri-io/src/test/resources/anonymous-c-levels.xml
ehri-ws/src/main/java/eu/ehri/project/ws/RepositoryResource.java
ehri-ws/src/main/java/eu/ehri/project/ws/errors/mappers/ValidationErrorMapper.java
ehri-ws/src/test/java/eu/ehri/project/ws/test/ImportResourceClientTest.java
ehri-ws/src/test/resources/anonymous-c-levels.xml

This caused issues because we didn't push an ID on the stack until we saw the <did> section, and that never happened, so the stack got confused. This didn't manifest itself unless the import was done in tolerant mode.
A second fix passes more info about *where* the error occurred to the web service.

Fixes for handling EADs with completely anonymous C-levels

---

ehri-io/src/main/resources/ead2002.properties
ehri-io/src/test/java/eu/ehri/project/importers/base/AbstractImporterTest.java
ehri-io/src/test/java/eu/ehri/project/importers/ead/EadHierarchicalMultipleDescriptionsTest.java
ehri-io/src/test/resources/photos-en-00.xml
ehri-io/src/test/resources/photos-uk-00.xml

This failed to import the `extentAndMedium` property from physFacet

Fix a missing trailing slash on ead2002 import properties

---

ehri-core/src/main/java/eu/ehri/project/models/Country.java
ehri-core/src/main/java/eu/ehri/project/models/cvoc/AuthoritativeSet.java
ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java

Previously, the `Country` type was not linkable. We don't typically link these, but some legacy links existed.
Additionally, the `Vocabulary` and `AuthoritativeSet` types have been made annotatable, which matches the GraphQL schema.

Fix GraphQL interface error and inconsistency.

---

ehri-io/src/main/java/eu/ehri/project/importers/json/BatchOperations.java
ehri-io/src/test/java/eu/ehri/project/importers/json/BatchOperationsTest.java

If, for example, we are given a list of IDs that have already been deleted, and we're in tolerant mode, we should not create a log if nothing actually gets changed.

Fix an issue where deletion logs could be created superfluously

---

ehri-core/src/test/java/eu/ehri/project/models/utils/UniqueAdjacencyAnnotationHandlerTest.java
ehri-ws/src/main/java/eu/ehri/project/ws/ToolsResource.java

Putting an item under another should remove the heldBy relationship, but this did not happen.

Fix an issue where reparenting items could leave repo heldBy intact

---

ehri-core/src/main/java/eu/ehri/project/persistence/BundleValidator.java
ehri-io/src/main/java/eu/ehri/project/utils/LanguageHelpers.java
ehri-io/src/test/java/eu/ehri/project/utils/LanguageHelpersTest.java
ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java
ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/messages.properties
ehri-ws-graphql/src/test/resources/testquery.graphql

This accepts 639-1 codes as well as 639-2 and is shorter and more tolerant to bad input.

Add a more usable (and succinct) `lang` param for GraphQL queries

---

ehri-ws-graphql/src/main/java/eu/ehri/project/graphql/GraphQLImpl.java

Instead leave it as a more precise alternative

Don't deprecate the `languageCode` field
